# Generated by Django 3.1.1 on 2020-09-28 15:49

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='airbnb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('adress', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=200)),
                ('owner_mail', models.EmailField(max_length=254)),
                ('house_photos', models.ImageField(upload_to='post/')),
                ('house_state', models.BooleanField(default=True)),
                ('arrival_date', models.DateField(default=datetime.date.today)),
                ('departure_date', models.DateField(default=datetime.date.today)),
                ('duration', models.DurationField()),
                ('SMOKING_CHOICES', models.CharField(choices=[('smoke', 'smoke'), ('not smoke', 'not smoke')], max_length=20)),
                ('ROOM_STATUES', models.CharField(choices=[('single', 'single'), ('double', 'double')], max_length=20)),
                ('room_price', models.FloatField(max_length=55)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
